version: '3.7'

services:
  ezm-redis:
    image: redis:latest
    restart: always
    container_name: ezm-redis
    expose:
      - 6379
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./database/redis.conf:/etc/redis/redis.conf
      - ./database/redis-data:/data/redis-data
    command: redis-server /etc/redis/redis.conf
  
  ezm-backend:
    build: ./backend
    restart: always
    container_name: ezm-backend
    expose:
      - 8000
    environment:
      TZ: Asia/Shanghai
    depends_on: 
      - ezm-redis
    volumes:
      - ./backend:/ez-movie/backend
    command:
      - /bin/sh
      - -c
      - |
        cd /ez-movie/backend
        uvicorn server:api --reload --host '0.0.0.0' --port 8000
  ezm-frontend:
    # TODO
    image: nginx:latest
    restart: always
    container_name: ezm-frontend
    ports:
      - 80:8080
    depends_on:
      - ezm-backend
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
